require 'awesome_explain/version'
require 'awesome_print'
require 'terminal-table'
require 'awesome_explain/utils/color'
require 'awesome_explain/renderers/mongoid'
require 'awesome_explain/kernel'
require 'awesome_explain/command_subscriber'
require 'awesome_explain/insights'
